substitutions:
  device_name: "esphome-bluetooth-proxy"
  friendly_name: "ESPHome Bluetooth Proxy"
  project_name: "esphome.bluetooth-proxy"
  project_version: "1.0-rc0"
  relay_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

api:

ota:

logger:

mdns:
  disabled: false

web_server:
  port: 80
  local: True

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://msquirogac/esphome-configs/bluetooth-proxy.yaml

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
