substitutions:
  device_name: "esphome-monitor"
  friendly_name: "ESPHome Monitor"
  project_name: "esphome.monitor"
  project_version: "1.0-rc0"

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true

api:

ota:

logger:

mdns:
  disabled: false

web_server:
  port: 80
  local: True

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://msquirogac/esphome-configs/monitor.yaml

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} RSSI"
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"
    disabled_by_default: true

button:
  - platform: restart
    name: "${friendly_name} Restart"

  - platform: factory_reset
    name: "${friendly_name} Factory Reset"
    disabled_by_default: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IPAddress"
      disabled_by_default: true

time:
  - platform: homeassistant
    id: homeassistant_time
