substitutions:
  device_name: "esphome-switch"
  friendly_name: "ESPHome Switch"
  project_name: "esphome.switch"
  project_version: "0.3"
  relay_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev
  restore_from_flash: true

api:

ota:

logger:

mdns:
  disabled: false

web_server:
  port: 80
  local: True

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://msquirogac/esphome-configs/sonoff-m5-120.yaml

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  - platform: gpio
    name: "${friendly_name} Button 1"
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay1

sensor:
  - platform: wifi_signal
    name: "${friendly_name} RSSI"
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"
    disabled_by_default: true

button:
  - platform: restart
    name: "${friendly_name} Restart"

  - platform: factory_reset
    name: "${friendly_name} Factory Reset"
    disabled_by_default: true

switch:
  - platform: gpio
    name: "${friendly_name} Relay 1"
    pin: GPIO23
    id: relay1
    restore_mode: ${relay_restore_mode}

light:
  - platform: status_led
    name: "${friendly_name} LED"
    id: blue_led
    internal: true
    pin:
      inverted: false
      number: GPIO5

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IPAddress"
      disabled_by_default: true

time:
  - platform: homeassistant
    id: homeassistant_time
