substitutions:
  device_name: "esphome-scale"
  friendly_name: "ESPHome Scale"
  project_name: "esphome.scale"
  project_version: "1.0-rc1"

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev
  framework:
    type: arduino

api:

ota:

logger:

mdns:
  disabled: false

web_server:
  port: 80
  local: True

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://msquirogac/esphome-configs/xiaomi-scale.yaml

esp32_ble_tracker:
  scan_parameters:
    interval: 160ms
    window: 60ms

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} RSSI"
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"
    disabled_by_default: true

  - platform: xiaomi_miscale
    mac_address: D0:3E:7D:11:03:4B
    weight:
      name: "${friendly_name} Weight"
    impedance:
      name: "${friendly_name} Impedance"
    #clear_impedance: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IPAddress"
      disabled_by_default: true
     
time:
  - platform: sntp
    id: my_time
